# Generated by Django 6.0.5 on 2026-07-03 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('category', 'Category'), ('subcategory', 'Subcategory'), ('tag', 'Tag')], default='tag', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tag.tag')),
            ],
            options={
                'db_table': 'tags_tag',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['parent', 'level'], name='forum_tag_parent_level_idx'), models.Index(fields=['slug'], name='forum_tag_slug_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_tag_name_per_parent')],
            },
        ),
    ]
