# Generated by Django 6.0.5 on 2026-06-20 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('subject_tag', models.CharField(blank=True, max_length=80, null=True)),
                ('formation_type', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_studygroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')], max_length=20)),
                ('meeting_url', models.TextField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='groups.studygroup')),
            ],
            options={
                'db_table': 'groups_meetinglink',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.studygroup')),
            ],
            options={
                'db_table': 'groups_membership',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
