# Generated by Django 6.0.5 on 2026-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('post_question', 'Post a Question'), ('submit_answer', 'Submit an Answer'), ('answer_endorsed', 'Answer Endorsed by Expert'), ('answer_accepted', 'Answer Accepted'), ('submit_resource', 'Submit a Resource'), ('resource_milestone', 'Resource Reached 10 Votes'), ('attend_session', 'Attended Study Group Session')], max_length=30)),
                ('points_awarded', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_pointtransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('streak_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'gamification_streakrecord',
                'ordering': ['-date'],
            },
        ),
    ]
