# Generated by Django 6.0.5 on 2026-07-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerdownvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='forum.answer'),
        ),
        migrations.AddField(
            model_name='answerdownvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerupvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='forum.answer'),
        ),
        migrations.AddField(
            model_name='answerupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.question'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', through='forum.QuestionTag', to='tag.tag'),
        ),
        migrations.AddField(
            model_name='questionupvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='forum.question'),
        ),
        migrations.AddField(
            model_name='questionupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='answerdownvote',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_answer_downvote'),
        ),
        migrations.AddConstraint(
            model_name='answerupvote',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_answer_upvote'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', '-created_at'], name='forum_answe_questio_60e4de_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author', '-created_at'], name='forum_answe_author__42058d_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('question', 'tag'), name='unique_question_tag'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='forum_quest_created_5bcd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-upvote_count'], name='forum_quest_upvote__4af157_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_resolved'], name='forum_quest_is_reso_ab4c01_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionupvote',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_question_upvote'),
        ),
    ]
