# Generated by Django 6.0.5 on 2026-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answer',
            new_name='forum_answe_questio_60e4de_idx',
            old_name='forum_ans_q_created_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='forum_quest_created_5bcd8a_idx',
            old_name='forum_quest_created_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='forum_quest_upvote__4af157_idx',
            old_name='forum_quest_upvote_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='forum_quest_is_reso_ab4c01_idx',
            old_name='forum_quest_resolv_idx',
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
