# Generated by Django 6.0.6 on 2026-06-11 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(blank=True, choices=[('textbook', 'Textbook'), ('article', 'Article'), ('video', 'Video'), ('website', 'Website'), ('other', 'Other')], max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=80, null=True)),
                ('net_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-net_votes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
